spring:
  application:
    name: forum
  datasource:
    url: jdbc:mysql://localhost:3306/forum
    username: trangnguyen
    password: S0meP@ssw0rdTh@tAreStr0ng
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
rest:
  user: /api/user
  system-code: /api/system-code
  post: /api/post
  issue: /api/issue
  comment: /api/comment

system-code:
  customer: CUSTOMER
  module: MODULE
  type: TYPE
  penpot-team: PENPOT_TEAM
  penpot-token: PENPOT_TOKEN

logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


penpot:
  api: https://design.penpot.app
  get-teams: /api/rpc/command/get-teams
  get-team-recent-files: /api/rpc/command/get-team-recent-files
  get-comment-threads: /api/rpc/command/get-comment-threads
  get-file-object-thumbnails: /api/rpc/command/get-file-object-thumbnails
  get-assets-by-id: /assets/by-id

minio:
  url: http://127.0.0.1:9000
  access:
    key: minioroot
    secret: minioroot
  bucket: forum
  image-size: 10485760
security:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437

