services:
  forum-db:
    container_name: forum-db
    image: mysql:lts
    ports:
      - "3306:3306"
    volumes:
      - "./mysql/data:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_PASSWORD: S0meP@ssw0rdTh@tAreStr0ng
      MYSQL_USER: trangnguyen
      MYSQL_ROOT_PASSWORD: S0meR00tP@sswordTh@tAreStr0ng
      MYSQL_DATABASE: forum
  forum-minio:
    container_name: forum-minio
    image: quay.io/minio/minio
    restart: unless-stopped
    volumes:
      - "./minio/data:/data"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioroot
      - MINIO_ROOT_PASSWORD=minioroot
    command: server /data --console-address ":9001"